# TensorFlow Basics

In [3]:
import tensorflow as tf

In [4]:
print(tf.__version__)

1.3.0


tensor is an n dimensional array

In [5]:
hello= tf.constant("hello")
world= tf.constant('world')

In [6]:
 type (hello)

tensorflow.python.framework.ops.Tensor

In [7]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [8]:
with tf.Session() as sess:
    result = sess.run(hello+world)

In [11]:
print (result)  #b means bytes literal

b'helloworld'


In [18]:
a=tf.constant(10)

In [19]:
b=tf.constant(700)

In [25]:
a+b

<tf.Tensor 'add_1:0' shape=() dtype=int32>

In [26]:
a+b

<tf.Tensor 'add_2:0' shape=() dtype=int32>

In [22]:
type(a)

tensorflow.python.framework.ops.Tensor

In [23]:
type (b)

tensorflow.python.framework.ops.Tensor

In [27]:
with tf.Session() as sess:
    result = sess.run(a+b)

In [28]:
result

710

In [29]:
const = tf.constant(10)

In [33]:
fill_mat = tf.fill((4,4),10)

In [34]:
myzeros = tf.zeros((4,4))

In [35]:
myones = tf.ones((4,4))

In [36]:
myrandn = tf.random_normal((4,4),mean=0,stddev=1.0)

In [39]:
myrandu = tf.random_uniform((4,4),minval=0,maxval=1)

In [40]:
myrandu

<tf.Tensor 'random_uniform:0' shape=(4, 4) dtype=float32>

In [42]:
my_ops = [const,fill_mat,myzeros,myones,myrandn,myrandu]

In [43]:
# interactive session

sess= tf.InteractiveSession()

In [44]:
for op in my_ops:
    print(sess.run(op))
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


[[-0.73900038 -1.23195112  0.67201263  0.22951359]
 [-0.86497104  0.60724014 -2.14281034 -0.39895689]
 [ 0.24726018  0.38530684 -0.25854805 -0.29453608]
 [-0.12252058  1.95535851  0.90845376 -0.22505975]]


[[ 0.11576509  0.04048717  0.1073674   0.12974834]
 [ 0.69915986  0.59412193  0.48068488  0.62555456]
 [ 0.54857957  0.37123597  0.23841667  0.95014298]
 [ 0.14803088  0.10218394  0.00150597  0.39792097]]




In [47]:
#eval method

for op in my_ops:
    print(op.eval())
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


[[ 1.00226808  0.38317001  0.03651494  0.24257243]
 [-1.28013957  1.50393593  0.15878519  0.61400807]
 [ 0.05591103  0.11544993 -0.05955259 -0.99274719]
 [-1.23982584 -0.49355927  1.07994139  0.74415153]]


[[ 0.55610549  0.25834346  0.74077785  0.788535  ]
 [ 0.42103255  0.93217814  0.92641485  0.93949878]
 [ 0.3183099   0.20507288  0.21603882  0.61544967]
 [ 0.84613812  0.45350838  0.03936851  0.51342869]]




In [48]:
a = tf.constant([ [1,2],
                  [3,4] ])

In [49]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [50]:
b= tf.constant([ [10] , [100] ])

In [51]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [52]:
result = tf.matmul(a,b)

In [53]:
sess.run(result)

array([[210],
       [430]])

In [55]:
result.eval()

array([[210],
       [430]])

In [56]:
result.get_shape()

TensorShape([Dimension(2), Dimension(1)])